### ISSUE TITLE
General Issue: Require older versions of jsonlite and jsonvalidate

### ISSUE THREAD

**Issue by NNaikp** [atorus-research/datasetjson#18]
### Background Information

The required versions of jsonlite and jsonvalidate are currently the latest available versions.
We do not have access to those readily available internally, but only through work-arounds.

Our internally available versions are:
jsonlite: 1.8.0 (or older)
jsonvalidate: 1.3.1 (or older)

Would it be possible to take a dependecncy to a older versions of these packages without breaking core functionalities?

**Comment by mstackhouse** [comment]
This will be fixed with #19 - no issues by updating version requirements.
