### ISSUE TITLE
Feature Request:  use pretty = FALSE by default

### ISSUE THREAD

**Issue by lexjansen** [atorus-research/datasetjson#20]
### Feature Idea

Since size has been a concern, it would be good to create Dataset-JSON files that are not 'pretty' formatted.
Current code:
  js <- jsonlite::toJSON(
    x,
    dataframe = "values",
    na = "null",
    auto_unbox = TRUE,
    pretty = pretty)

The default could be pretty = FALSE, with an option to override that behavior.

**Comment by mstackhouse** [comment]
Thanks for the reminder - I intended to change this.
