### ISSUE TITLE
Make schema validation optional or remove schema validation from read and write step

### ISSUE THREAD

**Issue by mstackhouse** [atorus-research/datasetjson#26]
On large file, schema validation can become prohibitive. So need away to bypass this to save the computational time.

**Comment by nicholas-masel** [comment]
@mstackhouse  What do you think here?  Optional or remove from read/write?

**Comment by mstackhouse** [comment]
I'd say just remove completely from read and write. There's limited added benefit of doing it on read, because if reading fails you can run the validator (which is what that error tells you to do anyway). And we're the ones writing out the file so I don't really think we need to run a validate on it.
