### ISSUE TITLE
fileOID is not directly tied to file path, so should not auto-default on write. 

### ISSUE THREAD

**Issue by mstackhouse** [atorus-research/datasetjson#3]

**Comment by lexjansen** [comment]
The issue and code seem to suggest that fileOID has any relation to a file location. This is not the case.
From the ODMv2 specification:

FileOIDs should be universally unique if at all possible. One way to ensure this is to prefix every FileOID with an internet domain name owned by the creator of the ODM file or database (followed by a forward slash, "/"). For example, FileOID="BestPharmaceuticals.com/Study5894/1" might be a good way to denote the first file in a series for study 5894 from Best Pharmaceuticals.

**Comment by mstackhouse** [comment]
- [ ] Remove automatic setting of fileOID within `write_dataset_json()`
- [ ] Update documentation to include explanation of the fileOID field description provided by @lexjansen
